--[[ Every command name and alias present in 6.4.2, extracted from the
     original source by tools/_analysis/analyze.py. Used by the coverage
     spec to prove the rewrite did not silently drop anything. ]]

return {
	{ "addalias" },
	{ "removealias" },
	{ "clraliases" },
	{ "discord", "support", "help" },
	{ "keepiy" },
	{ "unkeepiy" },
	{ "togglekeepiy" },
	{ "serverinfo", "info", "sinfo" },
	{ "jobid" },
	{ "notifyjobid" },
	{ "breakloops", "break" },
	{ "unloadiy", "unload", "killiy" },
	{ "gametp", "gameteleport" },
	{ "rejoin", "rj" },
	{ "inviteprompt" },
	{ "autorejoin", "autorj" },
	{ "serverhop", "shop" },
	{ "exit", "shutdown", "leave" },
	{ "noclip" },
	{ "unnoclip", "clip" },
	{ "togglenoclip" },
	{ "fly" },
	{ "flyspeed", "flysp" },
	{ "unfly", "nofly", "novfly", "unvehiclefly", "novehiclefly", "unvfly" },
	{ "vfly", "vehiclefly" },
	{ "togglevfly" },
	{ "vflyspeed", "vflysp", "vehicleflyspeed", "vehicleflysp" },
	{ "qefly", "flyqe" },
	{ "togglefly" },
	{ "cframefly", "cfly" },
	{ "uncframefly", "uncfly" },
	{ "cframeflyspeed", "cflyspeed" },
	{ "float", "platform" },
	{ "unfloat", "nofloat", "unplatform", "noplatform" },
	{ "togglefloat" },
	{ "swim" },
	{ "unswim", "noswim" },
	{ "toggleswim" },
	{ "setwaypoint", "swp", "setwp", "spos", "saveposition", "savepos" },
	{ "waypointpos", "wpp", "setwaypointposition", "setpos", "setwaypoint", "setwaypointpos" },
	{ "waypoints", "positions" },
	{ "showwaypoints", "showwp", "showwps" },
	{ "hidewaypoints", "hidewp", "hidewps" },
	{ "waypoint", "wp", "lpos", "loadposition", "loadpos" },
	{ "tweenspeed", "tspeed" },
	{ "tweenwaypoint", "twp" },
	{ "walktowaypoint", "wtwp" },
	{ "deletewaypoint", "dwp", "dpos", "deleteposition", "deletepos" },
	{ "clearwaypoints", "cwp", "clearpositions", "cpos", "clearpos" },
	{ "cleargamewaypoints", "cgamewp" },
	{ "enable" },
	{ "disable" },
	{ "showguis" },
	{ "unshowguis" },
	{ "hideguis" },
	{ "unhideguis" },
	{ "guidelete" },
	{ "unguidelete", "noguidelete" },
	{ "hideiy" },
	{ "showiy", "unhideiy" },
	{ "rec", "record" },
	{ "screenshot", "scrnshot" },
	{ "togglefs", "togglefullscreen" },
	{ "inspect", "examine" },
	{ "savegame", "saveplace" },
	{ "clearerror", "clearerrors" },
	{ "antigameplaypaused" },
	{ "unantigameplaypaused" },
	{ "clientantikick", "antikick" },
	{ "clientantiteleport", "antiteleport" },
	{ "allowrejoin", "allowrj" },
	{ "cancelteleport", "canceltp" },
	{ "volume", "vol" },
	{ "antilag", "boostfps", "lowgraphics" },
	{ "setfpscap", "fpscap", "maxfps" },
	{ "notify" },
	{ "lastcommand", "lastcmd" },
	{ "esp" },
	{ "espteam" },
	{ "noesp", "unesp", "unespteam" },
	{ "esptransparency" },
	{ "partesp" },
	{ "unpartesp", "nopartesp" },
	{ "chams" },
	{ "nochams", "unchams" },
	{ "locate" },
	{ "nolocate", "unlocate" },
	{ "view", "spectate" },
	{ "viewpart", "viewp" },
	{ "unview", "unspectate" },
	{ "freecam", "fc" },
	{ "freecampos", "fcpos", "fcp", "freecamposition", "fcposition" },
	{ "freecamwaypoint", "fcwp" },
	{ "freecamgoto", "fcgoto", "freecamtp", "fctp" },
	{ "unfreecam", "nofreecam", "unfc", "nofc" },
	{ "freecamspeed", "fcspeed" },
	{ "notifyfreecamposition", "notifyfcpos" },
	{ "copyfreecamposition", "copyfcpos" },
	{ "gotocamera", "gotocam", "tocam" },
	{ "tweengotocamera", "tweengotocam", "tgotocam", "ttocam" },
	{ "fov" },
	{ "lookat" },
	{ "fixcam", "restorecam" },
	{ "enableshiftlock", "enablesl", "shiftlock" },
	{ "firstp" },
	{ "thirdp" },
	{ "noclipcam", "nccam" },
	{ "maxzoom" },
	{ "minzoom" },
	{ "camdistance" },
	{ "unlockws", "unlockworkspace" },
	{ "lockws", "lockworkspace" },
	{ "delete", "remove" },
	{ "deleteclass", "removeclass", "deleteclassname", "removeclassname", "dc" },
	{ "chardelete", "charremove", "cd" },
	{ "chardeleteclass", "charremoveclass", "chardeleteclassname", "charremoveclassname", "cdc" },
	{ "deletevelocity", "dv", "removevelocity", "removeforces" },
	{ "deleteinvisparts", "deleteinvisibleparts", "dip" },
	{ "invisibleparts", "invisparts" },
	{ "uninvisibleparts", "uninvisparts" },
	{ "btools" },
	{ "f3x", "fex" },
	{ "partpath", "partname" },
	{ "antiafk", "antiidle" },
	{ "datalimit" },
	{ "replicationlag", "backtrack" },
	{ "noprompts", "nopurchaseprompts" },
	{ "showprompts", "showpurchaseprompts" },
	{ "promptr6" },
	{ "promptr15" },
	{ "wallwalk", "walkonwalls" },
	{ "age" },
	{ "chatage" },
	{ "joindate", "jd" },
	{ "chatjoindate", "cjd" },
	{ "copyname", "copyuser" },
	{ "userid", "id" },
	{ "copyplaceid", "placeid" },
	{ "copygameid", "gameid" },
	{ "copyid", "copyuserid" },
	{ "creatorid", "creator" },
	{ "copycreatorid", "copycreator" },
	{ "setcreatorid", "setcreator" },
	{ "appearanceid", "aid" },
	{ "copyappearanceid", "caid" },
	{ "norender" },
	{ "render" },
	{ "2022materials", "use2022materials" },
	{ "un2022materials", "unuse2022materials" },
	{ "goto", "to" },
	{ "tweengoto", "tgoto", "tto", "tweento" },
	{ "vehiclegoto", "vgoto", "vtp", "vehicletp" },
	{ "pulsetp", "ptp" },
	{ "vehiclenoclip", "vnoclip" },
	{ "vehicleclip", "vclip", "unvnoclip", "unvehiclenoclip" },
	{ "togglevnoclip" },
	{ "clientbring", "cbring" },
	{ "loopbring" },
	{ "unloopbring", "noloopbring" },
	{ "walkto", "follow" },
	{ "pathfindwalkto", "pathfindfollow" },
	{ "pathfindwalktowaypoint", "pathfindwalktowp" },
	{ "unwalkto", "nowalkto", "unfollow", "nofollow" },
	{ "orbit" },
	{ "unorbit" },
	{ "freeze", "fr" },
	{ "thaw", "unfreeze", "unfr" },
	{ "anchor" },
	{ "unanchor" },
	{ "loopoof" },
	{ "unloopoof" },
	{ "muteboombox" },
	{ "unmuteboombox" },
	{ "reset" },
	{ "freezeanims" },
	{ "unfreezeanims" },
	{ "respawn" },
	{ "refresh", "re" },
	{ "god" },
	{ "invisible", "invis" },
	{ "visible", "vis", "uninvisible" },
	{ "toggleinvis" },
	{ "toolinvisible", "toolinvis", "tinvis" },
	{ "strengthen" },
	{ "weaken" },
	{ "unweaken", "unstrengthen" },
	{ "breakvelocity" },
	{ "jpower", "jumppower", "jp" },
	{ "maxslopeangle", "msa" },
	{ "gravity", "grav" },
	{ "hipheight", "hheight" },
	{ "dance" },
	{ "undance", "nodance" },
	{ "nolimbs", "rlimbs" },
	{ "noarms", "rarms" },
	{ "nolegs", "rlegs" },
	{ "sit" },
	{ "lay", "laydown" },
	{ "sitwalk" },
	{ "nosit" },
	{ "unnosit" },
	{ "jump" },
	{ "infjump", "infinitejump" },
	{ "uninfjump", "uninfinitejump", "noinfjump", "noinfinitejump" },
	{ "flyjump" },
	{ "unflyjump", "noflyjump" },
	{ "autojump", "ajump" },
	{ "unautojump", "noautojump", "noajump", "unajump" },
	{ "edgejump", "ejump" },
	{ "unedgejump", "noedgejump", "noejump", "unejump" },
	{ "team" },
	{ "nobgui", "unbgui", "nobillboardgui", "unbillboardgui", "noname", "rohg" },
	{ "loopnobgui", "loopunbgui", "loopnobillboardgui", "loopunbillboardgui", "loopnoname", "looprohg" },
	{ "unloopnobgui", "unloopunbgui", "unloopnobillboardgui", "unloopunbillboardgui", "unloopnoname", "unlooprohg" },
	{ "spasm" },
	{ "unspasm", "nospasm" },
	{ "headthrow" },
	{ "animation", "anim" },
	{ "emote", "em" },
	{ "noanim" },
	{ "reanim" },
	{ "animspeed" },
	{ "copyanimation", "copyanim", "copyemote" },
	{ "copyanimationid", "copyanimid", "copyemoteid" },
	{ "stopanimations", "stopanims", "stopanim" },
	{ "refreshanimations", "refreshanimation", "refreshanims", "refreshanim" },
	{ "allowcustomanim", "allowcustomanimations" },
	{ "unallowcustomanim", "unallowcustomanimations" },
	{ "loopanimation", "loopanim" },
	{ "tpposition", "tppos" },
	{ "tweentpposition", "ttppos" },
	{ "offset" },
	{ "tweenoffset", "toffset" },
	{ "clickteleport" },
	{ "mouseteleport", "mousetp" },
	{ "tptool", "teleporttool" },
	{ "thru" },
	{ "clickdelete" },
	{ "getposition", "getpos", "notifypos", "notifyposition" },
	{ "copyposition", "copypos" },
	{ "walktopos", "walktoposition" },
	{ "speed", "ws", "walkspeed" },
	{ "spoofspeed", "spoofws", "spoofwalkspeed" },
	{ "loopspeed", "loopws" },
	{ "unloopspeed", "unloopws" },
	{ "spoofjumppower", "spoofjp" },
	{ "loopjumppower", "loopjp", "loopjpower" },
	{ "unloopjumppower", "unloopjp", "unloopjpower" },
	{ "tools", "gears" },
	{ "notools", "rtools", "clrtools", "removetools", "deletetools", "dtools" },
	{ "deleteselectedtool", "dst" },
	{ "console" },
	{ "oldconsole" },
	{ "explorer", "dex" },
	{ "moondex", "mdex" },
	{ "remotespy", "rspy", "cobalt", "cspy" },
	{ "simplespy", "sspy" },
	{ "audiologger", "alogger" },
	{ "loopgoto" },
	{ "unloopgoto", "noloopgoto" },
	{ "headsit" },
	{ "chat", "say" },
	{ "spam" },
	{ "nospam", "unspam" },
	{ "whisper", "pm" },
	{ "pmspam" },
	{ "nopmspam", "unpmspam" },
	{ "spamspeed" },
	{ "bubblechat" },
	{ "unbubblechat", "nobubblechat" },
	{ "chatwindow" },
	{ "unchatwindow", "nochatwindow" },
	{ "darkchat" },
	{ "blockhead" },
	{ "blockhats" },
	{ "blocktool" },
	{ "creeper" },
	{ "bang", "rape" },
	{ "unbang", "unrape" },
	{ "carpet" },
	{ "uncarpet", "nocarpet" },
	{ "friend" },
	{ "unfriend" },
	{ "bringpart" },
	{ "bringpartclass", "bpc" },
	{ "gotopart", "topart" },
	{ "tweengotopart", "tgotopart", "ttopart" },
	{ "gotopartclass", "gpc" },
	{ "tweengotopartclass", "tgpc" },
	{ "gotomodel", "tomodel" },
	{ "tweengotomodel", "tgotomodel", "ttomodel" },
	{ "gotopartdelay" },
	{ "noclickdetectorlimits", "nocdlimits", "removecdlimits" },
	{ "fireclickdetectors", "firecd", "firecds" },
	{ "noproximitypromptlimits", "nopplimits", "removepplimits" },
	{ "fireproximityprompts", "firepp" },
	{ "instantproximityprompts", "instantpp" },
	{ "uninstantproximityprompts", "uninstantpp" },
	{ "notifyping", "ping" },
	{ "grabtools" },
	{ "nograbtools", "ungrabtools" },
	{ "removespecifictool" },
	{ "unremovespecifictool" },
	{ "clearremovespecifictool" },
	{ "light" },
	{ "unlight", "nolight" },
	{ "copytools" },
	{ "naked" },
	{ "noface", "removeface" },
	{ "spawnpoint", "spawn" },
	{ "nospawnpoint", "nospawn", "removespawnpoint" },
	{ "flashback", "diedtp" },
	{ "hatspin", "spinhats" },
	{ "unhatspin", "unspinhats" },
	{ "clearhats", "cleanhats" },
	{ "split" },
	{ "nilchar" },
	{ "unnilchar", "nonilchar" },
	{ "noroot", "removeroot", "rroot" },
	{ "replaceroot", "replacerootpart" },
	{ "clearcharappearance", "clearchar", "clrchar" },
	{ "equiptools" },
	{ "unequiptools" },
	{ "dupetools", "clonetools" },
	{ "touchinterests", "touchinterest", "firetouchinterests", "firetouchinterest" },
	{ "fullbright", "fb", "fullbrightness" },
	{ "loopfullbright", "loopfb" },
	{ "unloopfullbright", "unloopfb" },
	{ "ambient" },
	{ "day" },
	{ "night" },
	{ "nofog" },
	{ "brightness" },
	{ "globalshadows", "gshadows" },
	{ "unglobalshadows", "nogshadows", "ungshadows", "noglobalshadows" },
	{ "restorelighting", "rlighting" },
	{ "stun", "platformstand" },
	{ "unstun", "nostun", "unplatformstand", "noplatformstand" },
	{ "norotate", "noautorotate" },
	{ "unnorotate", "autorotate" },
	{ "enablestate" },
	{ "disablestate" },
	{ "drophats", "drophat" },
	{ "deletehats", "nohats", "rhats" },
	{ "droptools", "droptool" },
	{ "droppabletools" },
	{ "reach" },
	{ "boxreach" },
	{ "unreach", "noreach", "unboxreach" },
	{ "grippos" },
	{ "usetools" },
	{ "logs" },
	{ "chatlogs", "clogs" },
	{ "joinlogs", "jlogs" },
	{ "chatlogswebhook", "logswebhook" },
	{ "fling" },
	{ "unfling", "nofling" },
	{ "togglefling" },
	{ "flyfling" },
	{ "unflyfling" },
	{ "toggleflyfling" },
	{ "walkfling" },
	{ "unwalkfling", "nowalkfling" },
	{ "togglewalkfling" },
	{ "invisfling" },
	{ "antifling" },
	{ "unantifling" },
	{ "toggleantifling" },
	{ "handlekill", "hkill" },
	{ "teleportwalk", "tpwalk" },
	{ "unteleportwalk", "untpwalk" },
	{ "spin" },
	{ "unspin" },
	{ "xray" },
	{ "unxray", "noxray" },
	{ "togglexray" },
	{ "loopxray" },
	{ "unloopxray" },
	{ "walltp" },
	{ "unwalltp", "nowalltp" },
	{ "autoclick" },
	{ "unautoclick", "noautoclick" },
	{ "mousesensitivity", "ms" },
	{ "hovername" },
	{ "unhovername", "nohovername" },
	{ "headsize" },
	{ "hitbox" },
	{ "hitboxes" },
	{ "unhitboxes" },
	{ "stareat", "stare" },
	{ "unstareat", "unstare", "nostare", "nostareat" },
	{ "rolewatch" },
	{ "rolewatchstop" },
	{ "rolewatchleave", "unrolewatch" },
	{ "staffwatch" },
	{ "unstaffwatch" },
	{ "findfriendgroups" },
	{ "removeterrain", "rterrain", "noterrain" },
	{ "clearnilinstances", "nonilinstances", "cni" },
	{ "destroyheight", "dh" },
	{ "antivoid" },
	{ "unantivoid", "noantivoid" },
	{ "fakeout" },
	{ "trip" },
	{ "removeads", "adblock" },
	{ "scare", "spook" },
	{ "alignmentkeys" },
	{ "unalignmentkeys", "noalignmentkeys" },
	{ "ctrllock" },
	{ "unctrllock" },
	{ "listento" },
	{ "unlistento" },
	{ "jerk" },
	{ "guiscale" },
	{ "muteallvoices", "muteallvcs" },
	{ "unmuteallvoices", "unmuteallvcs" },
	{ "mutevc" },
	{ "unmutevc" },
	{ "phonebook", "call" },
	{ "freezeunanchored", "freezeua" },
	{ "thawunanchored", "thawua", "unfreezeunanchored", "unfreezeua" },
	{ "tpunanchored", "tpua" },
	{ "autokeypress", "keypress" },
	{ "unautokeypress", "noautokeypress", "unkeypress", "nokeypress" },
	{ "addplugin", "plugin" },
	{ "removeplugin", "deleteplugin" },
	{ "reloadplugin" },
	{ "addallplugins", "loadallplugins" },
	{ "removecmd", "deletecmd" },
	{ "debug" },
}
