#!/usr/bin/env python3
"""
Infinite Yield build tool.

Produces, from src/:

  source            the single-file bundle users load with loadstring(HttpGet(...))
  loader.lua        the remote loader: fetches modules individually (dev channel)
  src/manifest.lua  generated module list, used by the remote loader
  tools/_build/sourcemap.json
                    bundle line ranges per module, so a traceback line number
                    can be mapped back to a source file

Both outputs embed the same src/runtime.lua and src/entry.lua bodies verbatim,
so module resolution and startup are identical in either mode.

    python3 tools/build.py            build everything
    python3 tools/build.py --check    build to a temp buffer and report only
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
BUILD_DIR = os.path.join(ROOT, "tools", "_build")

SPECIAL = {"runtime", "entry", "manifest"}

# The repository the built artifacts point at: the version check, the
# re-injection payload used by `;keepiy`, and the remote loader's module fetches
# all derive from this one value.
REPO = "CarlDV/infiniteyield"
REPO_URL = "https://github.com/" + REPO
REPO_RAW = "https://raw.githubusercontent.com/" + REPO + "/master/"


def read(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def module_name(path):
    rel = os.path.relpath(path, SRC).replace(os.sep, "/")
    return rel[:-4] if rel.endswith(".lua") else rel


def discover():
    """Every module under src/, sorted so builds are reproducible."""
    found = []
    for base, dirs, files in os.walk(SRC):
        dirs.sort()
        for name in sorted(files):
            if not name.endswith(".lua"):
                continue
            path = os.path.join(base, name)
            mod = module_name(path)
            if mod in SPECIAL:
                continue
            found.append((mod, path))
    found.sort(key=lambda entry: entry[0])
    return found


def read_version():
    path = os.path.join(ROOT, "version")
    try:
        data = json.loads(read(path))
        return data.get("Version", "0.0.0")
    except Exception:
        return "0.0.0"


def lua_string_list(names):
    return ",".join('"%s"' % name for name in names)


GUARD = """-- Infinite Yield {version} -- built {stamp}
-- {count} modules. Source: {repo}
-- This file is generated by tools/build.py. Edit src/ instead.
"""


def build_bundle(modules, version):
    runtime = read(os.path.join(SRC, "runtime.lua"))
    entry = read(os.path.join(SRC, "entry.lua"))

    out = []
    line = 1
    sourcemap = {}

    def emit(text):
        nonlocal line
        out.append(text)
        line += text.count("\n")

    emit(GUARD.format(version=version, stamp=time.strftime("%Y-%m-%d %H:%M:%S"),
                      count=len(modules), repo=REPO_URL))

    emit("local __IY_RUNTIME__ = (function(...)\n")
    emit(runtime)
    if not runtime.endswith("\n"):
        emit("\n")
    emit("end)()\n\n")

    emit('local IY = __IY_RUNTIME__.new({ version = "%s", channel = "release", bundled = true,'
         ' repo = "%s", base = "%s", entry = "source" })\n' % (version, REPO, REPO_RAW))
    emit("IY.manifest = { files = { %s } }\n\n" % lua_string_list([m for m, _ in modules]))

    for name, path in modules:
        body = read(path)
        emit('--[[iy:module %s]]\n' % name)
        emit('IY.define("%s", function(...)\n' % name)
        start = line
        emit(body)
        if not body.endswith("\n"):
            emit("\n")
        sourcemap[name] = [start, line - 1]
        emit("end)\n\n")

    emit("return (function(...)\n")
    emit(entry)
    if not entry.endswith("\n"):
        emit("\n")
    emit("end)(IY)\n")

    return "".join(out), sourcemap


LOADER_TEMPLATE = '''-- Infinite Yield remote loader ({version})
-- Fetches modules individually so a branch can be tested without rebuilding.
--   getgenv().IY_CONFIG = {{ branch = "my-branch", debug = true }}
--   loadstring(game:HttpGet("{raw}loader.lua"))()
-- The release entry point is `source`, which embeds these same modules.

local __IY_RUNTIME__ = (function(...)
{runtime}
end)()

local config = {{}}
do
\tlocal ok, genv = pcall(function() return getgenv and getgenv() or _G end)
\tif ok and type(genv) == "table" and type(genv.IY_CONFIG) == "table" then
\t\tfor key, value in pairs(genv.IY_CONFIG) do config[key] = value end
\tend
end
config.version = config.version or "{version}"
config.channel = config.channel or "remote"
config.branch  = config.branch or "master"
config.repo    = config.repo or "{repo}"
config.base    = config.base or ("https://raw.githubusercontent.com/" .. config.repo .. "/" .. config.branch .. "/")
config.entry   = config.entry or "loader.lua"

local IY = __IY_RUNTIME__.new(config)

local cache = {{}}

local function fetch(url)
\tif cache[url] then return cache[url] end
\tlocal attempts, lastError = 0, nil
\twhile attempts < 3 do
\t\tattempts = attempts + 1
\t\tlocal ok, body = pcall(function() return game:HttpGet(url, true) end)
\t\tif ok and type(body) == "string" and #body > 0 then
\t\t\tcache[url] = body
\t\t\treturn body
\t\tend
\t\tlastError = body
\t\ttask.wait(0.35 * attempts)
\tend
\terror("[iy] could not fetch " .. url .. ": " .. tostring(lastError), 0)
end

local manifestChunk = loadstring(fetch(config.base .. "src/manifest.lua"), "=iy/manifest")
IY.manifest = manifestChunk()

--[[ Modules are compiled on demand; the runtime memoises the result. ]]
IY.resolve = function(name)
\tlocal source = fetch(config.base .. "src/" .. name .. ".lua")
\tlocal chunk, err = loadstring(source, "=iy/" .. name)
\tif not chunk then
\t\terror("[iy] syntax error in " .. name .. ": " .. tostring(err), 0)
\tend
\treturn chunk
end

return (function(...)
{entry}
end)(IY)
'''


def build_loader(modules, version):
    runtime = read(os.path.join(SRC, "runtime.lua"))
    entry = read(os.path.join(SRC, "entry.lua"))
    return LOADER_TEMPLATE.format(version=version, runtime=runtime.rstrip("\n"),
                                 entry=entry.rstrip("\n"), raw=REPO_RAW, repo=REPO)


MANIFEST_TEMPLATE = '''--[[ Generated by tools/build.py. Do not edit.
     The remote loader reads this to know what to fetch. ]]
return {
\tversion = "%s",
\tgenerated = "%s",
\tfiles = {
%s
\t},
}
'''


def build_manifest(modules, version):
    lines = ",\n".join('\t\t"%s"' % name for name, _ in modules)
    return MANIFEST_TEMPLATE % (version, time.strftime("%Y-%m-%d"), lines)


def luajit_check(path, label):
    """Syntax-check a generated file if luajit is available."""
    try:
        result = subprocess.run(
            ["luajit", "-e", "local f,e=loadfile(%r) if not f then io.stderr:write(e) os.exit(1) end" % path],
            capture_output=True, text=True, timeout=120)
    except FileNotFoundError:
        print("  (luajit not found, skipping syntax check)")
        return True
    if result.returncode != 0:
        print("SYNTAX ERROR in %s:\n%s" % (label, result.stderr.strip()))
        return False
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="do not write outputs")
    args = parser.parse_args()

    modules = discover()
    version = read_version()
    if not modules:
        print("no modules found under src/")
        return 1

    bundle, sourcemap = build_bundle(modules, version)
    loader = build_loader(modules, version)
    manifest = build_manifest(modules, version)

    print("modules:      %d" % len(modules))
    print("bundle size:  %.1f KiB (%d lines)" % (len(bundle) / 1024, bundle.count("\n")))
    print("version:      %s" % version)

    if args.check:
        return 0

    os.makedirs(BUILD_DIR, exist_ok=True)
    with open(os.path.join(ROOT, "source"), "w", encoding="utf-8") as handle:
        handle.write(bundle)
    with open(os.path.join(ROOT, "loader.lua"), "w", encoding="utf-8") as handle:
        handle.write(loader)
    with open(os.path.join(SRC, "manifest.lua"), "w", encoding="utf-8") as handle:
        handle.write(manifest)
    with open(os.path.join(BUILD_DIR, "sourcemap.json"), "w", encoding="utf-8") as handle:
        json.dump({"version": version, "modules": sourcemap}, handle, indent=1)

    ok = luajit_check(os.path.join(ROOT, "source"), "source")
    ok = luajit_check(os.path.join(ROOT, "loader.lua"), "loader.lua") and ok
    print("wrote source, loader.lua, src/manifest.lua")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
