--[[═══════════════════════════════════════════════════════════════════════════
	tools/gendocs · generate docs/COMMANDS.md from the live registry
	─────────────────────────────────────────────────────────────────────────
	    luajit tools/gendocs.lua

	Boots the built bundle inside the test stub, asks the registry to export
	itself, and writes the reference. The command list can therefore never drift
	from the code -- which is exactly what happened to the legacy 436-row `CMDs`
	table that had to be edited by hand alongside every command.
═══════════════════════════════════════════════════════════════════════════]]

local ROOT = "."

local function readFile(path)
	local handle = io.open(path, "r")
	if not handle then return nil end
	local contents = handle:read("*a")
	handle:close()
	return contents
end

local Stub = dofile(ROOT .. "/tests/stub/init.lua")
local env = Stub.new({ playerName = "Docs", playerCount = 2, executor = "IYDocs" })

local source = readFile(ROOT .. "/source")
if not source then
	io.stderr:write("source bundle missing -- run python3 tools/build.py first\n")
	os.exit(1)
end

local chunk, err = loadstring(source, "@source")
if not chunk then
	io.stderr:write("bundle does not compile: " .. tostring(err) .. "\n")
	os.exit(1)
end
setfenv(chunk, env.globals)

local ok, result = pcall(chunk)
if not ok then
	io.stderr:write("bundle raised while loading: " .. tostring(result) .. "\n")
	os.exit(1)
end

env.scheduler.drain(20000)
env.scheduler.advance(2)
env.scheduler.drain(20000)

local IY = env.globals.IY
if not IY then
	io.stderr:write("the bundle did not expose a runtime\n")
	os.exit(1)
end

local Registry = IY.import("cmd/registry")
local Players = IY.import("core/players")
local commands = Registry.export()

-- ── group by category ───────────────────────────────────────────────────────

local categories, order = {}, {}
for i = 1, #commands do
	local entry = commands[i]
	if not entry.hidden then
		local bucket = categories[entry.category]
		if not bucket then
			bucket = {}
			categories[entry.category] = bucket
			order[#order + 1] = entry.category
		end
		bucket[#bucket + 1] = entry
	end
end
table.sort(order)

-- ── render ──────────────────────────────────────────────────────────────────

local out = {}
local function write(line)
	out[#out + 1] = line or ""
end

local visible = 0
for i = 1, #order do visible = visible + #categories[order[i]] end

write("# Command reference")
write()
write("Generated by `luajit tools/gendocs.lua` from the command registry. Do not")
write("edit by hand.")
write()
write(string.format("**%d commands** in %d categories, as of version %s.",
	visible, #order, tostring(IY.version)))
write()
write("Arguments in `<angle brackets>` are required, `[square brackets]` optional.")
write("A command with an `off` handler also has `un<name>`, `no<name>` and")
write("`toggle<name>`; those are listed with their parent rather than separately.")
write()

write("## Player selectors")
write()
write("Anywhere a command takes players you can use:")
write()
write("| Selector | Matches |")
write("|---|---|")
local selectors = Players.selectorHelp()
for i = 1, #selectors do
	write(string.format("| `%s` | %s |", selectors[i].token, selectors[i].describe))
end
write("| `bob` | name or display name, prefix matched (an exact match wins) |")
write("| `@bob` | account name only |")
write("| `1234567` | user id |")
write("| `bob,jim` | both groups |")
write("| `all-bob` | everyone except bob |")
write()

write("## Contents")
write()
for i = 1, #order do
	local category = order[i]
	write(string.format("- [%s](#%s) (%d)", category,
		string.lower((string.gsub(category, "%s+", "-"))), #categories[category]))
end
write()

for i = 1, #order do
	local category = order[i]
	local bucket = categories[category]
	table.sort(bucket, function(a, b) return a.name < b.name end)

	write("## " .. category)
	write()

	for b = 1, #bucket do
		local entry = bucket[b]
		local heading = "`" .. entry.signature .. "`"
		write("### " .. heading)
		write()
		if entry.description ~= "" then
			write(entry.description)
			write()
		end
		if #entry.aliases > 0 then
			write("**Aliases:** `" .. table.concat(entry.aliases, "`, `") .. "`")
			write()
		end
		if #entry.args > 0 then
			write("| Argument | Type | Default |")
			write("|---|---|---|")
			for a = 1, #entry.args do
				local spec = entry.args[a]
				local default = spec.default
				if default == nil then
					default = spec.optional and "_optional_" or "_required_"
				else
					default = "`" .. tostring(default) .. "`"
				end
				write(string.format("| `%s` | %s | %s |", spec.name, spec.describe, default))
			end
			write()
		end
		local requires = entry.requires or {}
		local notes = {}
		if requires.character then notes[#notes + 1] = "needs a character" end
		if requires.alive then notes[#notes + 1] = "needs to be alive" end
		if requires.tool then notes[#notes + 1] = "needs a tool" end
		if requires.persist then notes[#notes + 1] = "needs file access" end
		if requires.desktop then notes[#notes + 1] = "computer only" end
		if requires.capability then
			local list = type(requires.capability) == "table" and requires.capability
				or { requires.capability }
			notes[#notes + 1] = "needs executor support for `" .. table.concat(list, "`, `") .. "`"
		end
		if #notes > 0 then
			write("_" .. table.concat(notes, "; ") .. "._")
			write()
		end
		for e = 1, #entry.examples do
			write("```")
			write(";" .. entry.examples[e])
			write("```")
		end
		if #entry.examples > 0 then write() end
	end
end

local handle = io.open(ROOT .. "/docs/COMMANDS.md", "w")
if not handle then
	io.stderr:write("could not write docs/COMMANDS.md\n")
	os.exit(1)
end
handle:write(table.concat(out, "\n"))
handle:write("\n")
handle:close()

io.write(string.format("wrote docs/COMMANDS.md: %d commands, %d categories\n", visible, #order))
